#-------------------------------
# General Site Settings
title: oiNacs
logo: logo2.jpeg # You can add own logo.
description: Better App Life with oiNacs. Simple with Free Apps.


#-------------------------------
# Author Settings
author:
  name: oiNacs
  image: main_introduce.jpg
  say-hello: Hello, We are <strong>[ o i N a c s ]</strong>
  bio: Just as there are clothes that suit me no matter how good it looks, We have to find a style that suits me. Let`s dispose of unnecessary things and implement <strong>"meaningful minimalism"</strong> that fits your style with just your favorite things! Minimalism that suits me. Simple life. Simple app. It`s <a href="about"> oiNacs</a>.
  #bio: Designs, talks, playing music, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design, free resources and inspiration. Loves <a href="#">music</a> & play Piano.


#-------------------------------
# Contact links
twitter: https://twitter.com/oinacs1 # Add your Twitter handle
facebook: https://www.facebook.com/OINacs-101054385395254 # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: masteroinacs # add your shortname for Disqus Comment. For example mr-brown
layout: default
comments: true


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-0T2K0KDZ1L # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
